#ifndef _ONVIF_ERROR_RESPONES
#define _ONVIF_ERROR_RESPONES

#include "onvif.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ERR_SENDER              "s:Sender"
#define ERR_RECEIVER            "s:Receiver"
#define ERR_VERSIONMISMATCH     "s:VersionMismatch"
#define ERR_MUSTUNDERSTAND      "s:MustUnderstand"
#define ERR_DATAENCODINGUNKNOWN "s:DataEncodingUnknown"

#define ERR_INVALIDARGS         "ter:InvalidArgs"
#define ERR_INVALIDARGVAL       "ter:InvalidArgVal"
#define ERR_ACTION              "ter:Action"
#define ERR_ACTIONNOTSUPPORTED  "ter:ActionNotSupported"
#define ERR_OUTOFMEMORY         "ter:OutofMemory"
#define ERR_NOTAUTHORIZED       "ter:NotAuthorized"
#define ERR_UNKNOWNACTION       "ter:UnknownAction"
#define ERR_WELLFORMED          "ter:WellFormed"
#define ERR_TAGMISMATCH         "ter:TagMismatch"
#define ERR_TAG                 "ter:Tag"
#define ERR_NAMESPACE           "ter:Namespace"
#define ERR_MISSINGATTR         "ter:MissingAttr"
#define ERR_PROHIBATTR          "ter:ProhibAttr"
#define ERR_OPERATIONPROHIBITED "ter:OperationProhibited"
#define ERR_CRITICALERROR       "ter:CriticalError"

typedef enum 
{
	ONVIF_OK = 0,
	ONVIF_ERR_INVALID_IPV4_ADDR = -1,
	ONVIF_ERR_INVALID_IPV6_ADDR = -2,
	ONVIF_ERR_INVALID_DNS_NAME = -3,
	ONVIF_ERR_SERVICE_NOT_SUPPORT = -4,
	ONVIF_ERR_PORT_ALREADY_INUSE = -5,
	ONVIF_ERR_INVALID_GATEWAY_ADDR = -6,
	ONVIF_ERR_INVALID_HOSTNAME = -7,
	ONVIF_ERR_MISSINGATTR = -8,
	ONVIF_ERR_INVALID_DATETIME = -9,
	ONVIF_ERR_INVALID_TIMEZONE = -10,
	ONVIF_ERR_PROFILE_EXISTS = -11,
	ONVIF_ERR_MAX_NVT_PROFILES = -12,
	ONVIF_ERR_NO_PROFILE = -13,
	ONVIF_ERR_DEL_FIX_PROFILE = -14,
	ONVIF_ERR_NO_CONFIG = -15,
	ONVIF_ERR_NO_PTZ_PROFILE = -16,
	ONVIF_ERR_NO_HOME_POSITION = -17,
	ONVIF_ERR_NO_TOKEN = - 18,
	ONVIF_ERR_PRESET_EXIST = -19,
	ONVIF_ERR_TOO_MANY_PRESETS = -20,
	ONVIF_ERR_MOVING_PTZ = -21,
	ONVIF_ERR_NO_ENTITY = -22,
	ONVIF_ERR_INVALID_NETWORK_INTERFACE = -23, 
	ONVIF_ERR_INVALID_MTU_VALUE = -24,
	ONVIF_ERR_CONFIG_MODIFY = -25,
	ONVIF_ERR_CONFIGURATION_CONFLICT = -26,
	ONVIF_ERR_INVALID_POSIION = -27,
	ONVIF_ERR_TOO_MANY_SCOPES = -28,
	ONVIF_ERR_FIXED_SCOPE = -29,
	ONVIF_ERR_NO_SCOPE = -30,
	ONVIF_ERR_SCOPE_OVERWRITE = -31,
	ONVIF_ERR_RESOURCE_UNKNOWN_FAULT = -32,
	ONVIF_ERR_NO_SOURCE = -33,
	ONVIF_ERR_CANNOT_OVERWRITE_HOME = -34,
	ONVIF_ERR_SETTINGS_INVALID = -35,
	ONVIF_ERR_NO_IMAGEING_FOR_SOURCE = -36,
	ONVIF_ERR_USERNAME_EXIST = -37,
	ONVIF_ERR_PASSWORD_TOO_LONG = -38,
	ONVIF_ERR_USERNAME_TOO_LONG = -39,
	ONVIF_ERR_PASSWORD = -40,
	ONVIF_ERR_TOO_MANY_USERS = -41,
	ONVIF_ERR_ANONYMOUS_NOT_ALLOWED = -42,
	ONVIF_ERR_USERNAME_TOO_SHORT = -43,
	ONVIF_ERR_USERNAME_MISSING = -44,
	ONVIF_ERR_FIXED_USER = -45,
	ONVIF_ERR_MAX_OSDS = -46,
	ONVIF_ERR_NOT_AUTH = -47,
	ONVIF_ERR_DEFAULT = -48,
} ONVIF_ERROR_CODE;

typedef struct {
	HTTPTYPE contentType;
} ERROR_MSG;

int onviBuildErrReponse(int sockFd, ERROR_MSG errMsg, ONVIF_ERROR_CODE errCode);

#ifdef __cplusplus
}
#endif


#endif
